name: hellowayland
version: 'master'
summary: Test python3 with gtk3 in a snap on wayland
description: |
  This snap tests a helloworld program written in python3 and Gtk3 on Wayland
architectures:
  - amd64
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  hellowayland:
    command: desktop-launch $SNAP/bin/hellowayland
    plugs: [x11, unity7, wayland, desktop]

parts:
  gnome-3-26:
    plugin: nil
    override-pull: |
      apt-get install software-properties-common -y
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt-get update
      apt-get upgrade -yqq
  desktop-gtk3:
    after: [gnome-3-26]

  hellowayland:
    after: [gnome-3-26, desktop-gtk3]
    source: .
    # See 'snapcraft plugins'
    plugin: python
    stage-packages:
      - python3-gi
      - libcanberra-gtk3-module
      - gir1.2-gtk-3.0
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-dev

# For this to work on wayland at the moment you have to
# include the gnome-3-26 part or you may remove it if you use an LXD container
# or virtual machine and add the Gnome 3.26
# PPA to the container and do an apt update and apt upgrade before
# running snapcraft inside the container
