name: hellowayland
base: core24
version: 'master'
summary: Test python3 with gtk3 in a snap on wayland
description: |
  This snap tests a helloworld program written in python3 and Gtk3 on Wayland
platforms:
  - build-on: amd64
    build-for: arm64
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  hellowayland:
    # See 'snapcraft plugins'
    plugin: python
    source: .
    stage-packages:
       - python3-gi
       - python3-xdg
       - libcanberra-gtk3-module
       - gir1.2-gtk-3.0
    after: [desktop-gtk3]

  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3

apps:
  hellowayland:
    command: desktop-launch $SNAP/bin/hellowayland
    plugs: [x11, unity7, wayland, desktop]
